services:
  db:
    image: postgres:15
    container_name: sgd_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sgd_network

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sgd_web
    restart: unless-stopped

    command: >
      uv run gunicorn
      SGD.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --timeout 120

    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    depends_on:
      - db

    volumes:
      - static_volume:/app/sistemaGerenciadorDojo/staticfiles

    networks:
      - sgd_network

  nginx:
    image: nginx:1.27-alpine
    container_name: sgd_nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - staticfiles:/app/staticfiles:ro
      - static_volume:/static
      - ./certbot/www:/var/www/certbot      # SEM :ro, para o Certbot escrever
      - ./certbot/conf:/etc/letsencrypt 


    depends_on:
      - web

    networks:
      - sgd_network

volumes:
  postgres_data:
  staticfiles:
  certbot_www:
  letsencrypt:
  static_volume:


networks:
  sgd_network:
    driver: bridge