services:
  web:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sgd_web
    restart: unless-stopped

    command: >
      uv run gunicorn
      SGD.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --timeout 120

    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      ORACLE_ADMIN_PASSWORD: ${ORACLE_ADMIN_PASSWORD}       
      ORACLE_WALLET_PASSWORD: ${ORACLE_WALLET_PASSWORD} 

    volumes:
      - static_volume:/app/sistemaGerenciadorDojo/staticfiles
      - /home/ubuntu/wallet_dojo:/app/wallet_dojo:ro

    networks:
      - sgd_network

  nginx:
    image: nginx:1.27-alpine
    container_name: sgd_nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - staticfiles:/app/staticfiles:ro
      - static_volume:/static
      - ./certbot/www:/var/www/certbot      # SEM :ro, para o Certbot escrever
      - ./certbot/conf:/etc/letsencrypt 


    depends_on:
      - web

    networks:
      - sgd_network

volumes:
  staticfiles:
  certbot_www:
  letsencrypt:
  static_volume:


networks:
  sgd_network:
    driver: bridge