# Generated by Django 6.0.3 on 2026-03-17 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modalidade', models.CharField(default='Jiu-Jitsu', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoKravMaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_ingresso', models.DateTimeField()),
                ('data_nascimento', models.DateTimeField()),
                ('cor_faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('AMARELA', 'Amarela'), ('LARANJA', 'Laranja'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], default='BRANCA', max_length=20)),
                ('telefone', models.CharField(max_length=60)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoJudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_ingresso', models.DateTimeField()),
                ('data_nascimento', models.DateTimeField()),
                ('cor_faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA', 'Cinza'), ('AZUL', 'Azul'), ('AMARELA', 'Amarela'), ('LARANJA', 'Laranja'), ('VERDE', 'Verde'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], default='BRANCA', max_length=20)),
                ('telefone', models.CharField(max_length=60)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoJiuJitsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_ingresso', models.DateTimeField()),
                ('data_nascimento', models.DateTimeField()),
                ('cor_faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza_branca', 'Cinza e branca'), ('cinza', 'Cinza'), ('cinza_preta', 'Cinza e preta'), ('amarela_branca', 'Amarela e branca'), ('amarela', 'Amarela'), ('amarela_preta', 'Amarela e preta'), ('laranja_branca', 'Laranja e branca'), ('laranja', 'Laranja'), ('laranja_preta', 'Laranja e preta'), ('verde_branca', 'Verde e branca'), ('verde', 'Verde'), ('verde_preta', 'Verde e preta'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], default='branca', max_length=20)),
                ('telefone', models.CharField(max_length=60)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.modalidade')),
            ],
        ),
    ]
