# Generated by Django 6.0.3 on 2026-03-17 05:37

import alunos.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunojudo',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='alunokravmaga',
            name='modalidade',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_ingresso', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('cor_faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza_branca', 'Cinza e branca'), ('cinza', 'Cinza'), ('cinza_preta', 'Cinza e preta'), ('amarela_branca', 'Amarela e branca'), ('amarela', 'Amarela'), ('amarela_preta', 'Amarela e preta'), ('laranja_branca', 'Laranja e branca'), ('laranja', 'Laranja'), ('laranja_preta', 'Laranja e preta'), ('verde_branca', 'Verde e branca'), ('verde', 'Verde'), ('verde_preta', 'Verde e preta'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], default='branca', max_length=30)),
                ('telefone', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_emergencia', models.CharField(blank=True, help_text='Nome e telefone de contato', max_length=100, null=True)),
                ('mensalidade_em_dia', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.modalidade')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês correspondente ao pagamento')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.DeleteModel(
            name='AlunoJiuJitsu',
        ),
        migrations.DeleteModel(
            name='AlunoJudo',
        ),
        migrations.DeleteModel(
            name='AlunoKravMaga',
        ),
    ]
