# Generated by Django 6.0.3 on 2026-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_faixa_cor_faixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='faixa_atual',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='modalidade',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='is_active',
            new_name='aluno_ativo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=True, max_length=60, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa',
            field=models.CharField(choices=[('branca', 'Branca'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta'), ('cinza', 'Cinza'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde')], default='branca', max_length=10, verbose_name='Cor da Faixa'),
        ),
        migrations.DeleteModel(
            name='Faixa',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
