# Generated by Django 6.0.3 on 2026-04-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_aluno_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='contato_emergencia',
            field=models.CharField(default='', max_length=60, verbose_name='Contato de Emergência'),
        ),
    ]
