# Generated by Django 6.0.3 on 2026-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_aluno_contato_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='contato_emergencia',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Contato de Emergência'),
        ),
    ]
