# Generated by Django 6.0.3 on 2026-05-09 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_alter_aluno_contato_emergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=280.0, max_digits=8)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('mes_referencia', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
    ]
