"""
Django settings for SGD project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os

# =============================================================================
# Paths
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# Security
# =============================================================================

SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    "163.176.2.22",
    "localhost",
    "127.0.0.1",
    "ornellasdojo.flashhub.net",
]


# =============================================================================
# Application definition
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "alunos.apps.AlunosConfig",
    "django_crontab",
]
CRONJOBS = [
    (
        "* * * * *",
        "/app/cron_command.sh send_monthly_fee_reminder",
        ">> /var/log/django_cron.log 2>&1",
    )
]

LOGIN_REDIRECT_URL = "/admin/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SGD.urls"

CSRF_TRUSTED_ORIGINS = [
    "https://ornellasdojo.flashhub.net",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "SGD.wsgi.application"


# =============================================================================
# Database
# =============================================================================
WALLET_DIR = '/app/wallet_dojo'  # ajuste se seu HOME for diferente

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'dojodb_high',          # <-- nome à esquerda do '=' no tnsnames.ora
        'USER': 'ADMIN',
        'PASSWORD': os.environ.get('ORACLE_ADMIN_PASSWORD'),
        'OPTIONS': {
            'config_dir': WALLET_DIR,
            'wallet_location': WALLET_DIR,
            'wallet_password': os.environ.get('ORACLE_WALLET_PASSWORD'),
        },
    }
}


# =============================================================================
# Password validation
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# =============================================================================
# Internationalization
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# =============================================================================
# Static files
# =============================================================================
STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# =============================================================================
# Default primary key field type
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
