# Generated by Django 6.0.3 on 2026-03-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_alunojudo_modalidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='contato_emergencia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
