# Generated by Django 6.0.3 on 2026-03-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_options_remove_aluno_contato_emergencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cor_faixa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_ingresso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='modalidade',
            name='nome_modalidade',
        ),
        migrations.AddField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(default='Jiu-Jitsu', max_length=60, verbose_name='Nome da Modalidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='mensalidade_em_dia',
            field=models.BooleanField(default=False, verbose_name='Mensalidade em Dia'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=60, verbose_name='Telefone'),
        ),
        migrations.AlterModelTable(
            name='aluno',
            table='aluno',
        ),
        migrations.AlterModelTable(
            name='modalidade',
            table='modalidade',
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Faixa')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='alunos.modalidade', verbose_name='Modalidade')),
            ],
            options={
                'db_table': 'faixa',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ingresso', models.DateField(verbose_name='Data de Ingresso')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.aluno', verbose_name='Aluno')),
                ('faixa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.faixa', verbose_name='Faixa Atual')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.modalidade', verbose_name='Modalidade')),
            ],
            options={
                'db_table': 'matriculas',
                'unique_together': {('aluno', 'modalidade')},
            },
        ),
    ]
