# Generated by Django 6.0.3 on 2026-03-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_remove_aluno_cor_faixa_remove_aluno_data_ingresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='cor_faixa',
            field=models.CharField(default='Branca', max_length=50, verbose_name='Cor da Faixa'),
        ),
    ]
