# Generated by Django 6.0.3 on 2026-04-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_remove_matricula_faixa_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='modalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='alunos.modalidade'),
        ),
    ]
