# Generated by Django 6.0.3 on 2026-05-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagamentos', to='alunos.aluno'),
        ),
    ]
